<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="3" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-02-09T12:45:25 IST" name="Suite" finished-at="2025-02-09T12:45:46 IST" duration-ms="21076">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationTest.incorrectCreds()[pri:0, instance:AutomationFramework.tests.ErrorValidationTest@1b39fd82]" name="incorrectCreds" class="AutomationFramework.tests.ErrorValidationTest"/>
      </group> <!-- ErrorHandling -->
    </groups>
    <test started-at="2025-02-09T12:45:25 IST" name="ErrorValidation Test" finished-at="2025-02-09T12:45:46 IST" duration-ms="21076">
      <class name="AutomationFramework.tests.ErrorValidationTest">
        <test-method is-config="true" signature="launchapp()[pri:0, instance:AutomationFramework.tests.ErrorValidationTest@1b39fd82]" started-at="2025-02-09T12:45:25 IST" name="launchapp" finished-at="2025-02-09T12:45:28 IST" duration-ms="2625" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchapp -->
        <test-method signature="ProductErrorValidation()[pri:0, instance:AutomationFramework.tests.ErrorValidationTest@1b39fd82]" started-at="2025-02-09T12:45:28 IST" name="ProductErrorValidation" finished-at="2025-02-09T12:45:41 IST" duration-ms="12891" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:AutomationFramework.tests.ErrorValidationTest@1b39fd82]" started-at="2025-02-09T12:45:41 IST" name="teardown" finished-at="2025-02-09T12:45:41 IST" duration-ms="219" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="launchapp()[pri:0, instance:AutomationFramework.tests.ErrorValidationTest@1b39fd82]" started-at="2025-02-09T12:45:41 IST" name="launchapp" finished-at="2025-02-09T12:45:43 IST" duration-ms="2030" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchapp -->
        <test-method retried="true" signature="incorrectCreds()[pri:0, instance:AutomationFramework.tests.ErrorValidationTest@1b39fd82]" started-at="2025-02-09T12:45:43 IST" name="incorrectCreds" finished-at="2025-02-09T12:45:43 IST" duration-ms="408" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrects email or password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrects email or password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:99)
at AutomationFramework.tests.ErrorValidationTest.incorrectCreds(ErrorValidationTest.java:63)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- incorrectCreds -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:AutomationFramework.tests.ErrorValidationTest@1b39fd82]" started-at="2025-02-09T12:45:43 IST" name="teardown" finished-at="2025-02-09T12:45:43 IST" duration-ms="154" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="launchapp()[pri:0, instance:AutomationFramework.tests.ErrorValidationTest@1b39fd82]" started-at="2025-02-09T12:45:43 IST" name="launchapp" finished-at="2025-02-09T12:45:45 IST" duration-ms="1959" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchapp -->
        <test-method signature="incorrectCreds()[pri:0, instance:AutomationFramework.tests.ErrorValidationTest@1b39fd82]" started-at="2025-02-09T12:45:45 IST" name="incorrectCreds" finished-at="2025-02-09T12:45:46 IST" duration-ms="413" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrects email or password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrects email or password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:99)
at AutomationFramework.tests.ErrorValidationTest.incorrectCreds(ErrorValidationTest.java:63)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- incorrectCreds -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:AutomationFramework.tests.ErrorValidationTest@1b39fd82]" started-at="2025-02-09T12:45:46 IST" name="teardown" finished-at="2025-02-09T12:45:46 IST" duration-ms="165" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- AutomationFramework.tests.ErrorValidationTest -->
    </test> <!-- ErrorValidation Test -->
  </suite> <!-- Suite -->
</testng-results>
