<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<<<<<<< HEAD
<testsuite hostname="DESKTOP-6BCGIB4" failures="0" tests="2" name="AutomationFramework.tests.ErrorValidationTest" time="22.470" errors="0" timestamp="2025-02-09T16:52:47 IST" skipped="0">
  <testcase classname="AutomationFramework.tests.ErrorValidationTest" name="ProductErrorValidation" time="16.277"/>
  <system-out/>
  <testcase classname="AutomationFramework.tests.ErrorValidationTest" name="incorrectCreds" time="6.193"/>
=======
<testsuite hostname="WS-19080" failures="0" tests="2" name="AutomationFramework.tests.ErrorValidationTest" time="19.753" errors="0" timestamp="2025-02-09T21:19:37 IST" skipped="0">
  <testcase classname="AutomationFramework.tests.ErrorValidationTest" name="ProductErrorValidation" time="17.274"/>
  <system-out/>
  <testcase classname="AutomationFramework.tests.ErrorValidationTest" name="incorrectCreds" time="2.479"/>
>>>>>>> 2760f21 (Handled Exception code)
  <system-out/>
</testsuite> <!-- AutomationFramework.tests.ErrorValidationTest -->
