<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<<<<<<< HEAD
<testsuite hostname="DESKTOP-6BCGIB4" failures="0" tests="4" name="AutomationFramework.tests.SubmitorderTest" time="40.955" errors="0" timestamp="2025-02-08T19:23:56 IST" skipped="0">
  <testcase classname="AutomationFramework.tests.SubmitorderTest" name="submitorder" time="19.356"/>
  <system-out/>
  <testcase classname="AutomationFramework.tests.SubmitorderTest" name="submitorder" time="15.766"/>
  <system-out/>
  <testcase classname="AutomationFramework.tests.SubmitorderTest" name="Verifyorder" time="2.969"/>
  <system-out/>
  <testcase classname="AutomationFramework.tests.SubmitorderTest" name="Verifyorder" time="2.864"/>
=======
<testsuite hostname="WS-19080" failures="0" tests="4" name="AutomationFramework.tests.SubmitorderTest" time="36.504" errors="0" timestamp="2025-02-09T21:19:37 IST" skipped="0">
  <testcase classname="AutomationFramework.tests.SubmitorderTest" name="submitorder" time="16.153"/>
  <system-out/>
  <testcase classname="AutomationFramework.tests.SubmitorderTest" name="submitorder" time="15.135"/>
  <system-out/>
  <testcase classname="AutomationFramework.tests.SubmitorderTest" name="Verifyorder" time="2.515"/>
  <system-out/>
  <testcase classname="AutomationFramework.tests.SubmitorderTest" name="Verifyorder" time="2.701"/>
>>>>>>> 2760f21 (Handled Exception code)
  <system-out/>
</testsuite> <!-- AutomationFramework.tests.SubmitorderTest -->
